### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by seawatts** [ScribeLabsAI/amazon-trp-node#56]
It looks like the last version that was published to NPM was 2 years ago `v1.0.0`.

**Comment by EHadoux** [comment]
Hey, yeah indeed. However the version on GitHub's package manager is much more recent. https://github.com/ScribeLabsAI/amazon-trp-node/pkgs/npm/amazon-trp

**Comment by EHadoux** [comment]
We do accept PRs if you feel like setting up the config for dual publishing though.
